WEB/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    
    # blueprint
    from WEB.views import main_views, time_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(time_views.bp)
    
    return app

WEB/views/main_views.py
from flask import Blueprint, render_template

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def main():
    return render_template('main.html')

WEB/views/time_views.py
from flask import Blueprint, render_template, request
from API import Odsay
import pandas as pd

bp = Blueprint('time', __name__, url_prefix='/time')

color_dic = {'1호선': '#0052A4', '2호선': '#00A84D',
'3호선': '#EF7C1C', '4호선': '#00A4E3', '5호선': '#996CAC',
'6호선': '#CD7C2F', '7호선': '#747F00', '8호선': '#E6186C',
'9호선': '#BDB092'}

@bp.route('/')
def main():
    return render_template('main/time.html')

@bp.route('/', methods=['POST', 'GET'])
def result():
    
    start_station = request.form.get('start_station')
    end_station = request.form.get('end_station')
            
    
    if start_station[-1] == "역":
        start_station = start_station[:-1]
    
    if end_station[-1] == "역":
        end_station = end_station[:-1]
    
    if start_station == "서울역":
        start_station = "서울역"
    
    if end_station == "서울역":
        end_station = "서울역"
        
    if start_station == "서울":
        start_station = "서울역"
    
    if end_station == "서울":
        end_station = "서울역"
    
    
    SID, EID = Odsay.SID_EID(start_station, end_station) # SID, EID 구하는 함수
    df_stations, drive_info_df = Odsay.metrojson(SID, EID) # Odsay Data 구하는 함수
    station_ls = Odsay.station_list(df_stations)
    
    # 시간 받는 거
    
    congestion_ls = [] # 재영님이 주실 것
    split_stations, split_congestion, split_minute, percent_ls, lane = Odsay.result_list(df_stations, drive_info_df, congestion_ls)
    
    cogestion_mapping = {}
    color_ls = list(pd.Series(lane).replace(color_dic))

    # < 결과 예시 >
    # split_stations = [['서울역', '회현', '명동', '충무로'], (환승) ['동대문역사문화공원', '신당', '상왕십리', '왕십리', '한양대']]
    # split_congestion = [[12, 34, 1, 99], (환승) [12, 34, 34, 24, 11]]
    # lane = ['4호선', '2호선']
    # travel_time_ls = [2, 4, 5, 7, 10, 12, 13, 15, 17] -> 이동 시간
    # split_minute = [[2, 4, 5, 7], (환승) [10, 12, 13, 15, 17]] -> 
    # percent_ls = [11.76470588235294, 11.76470588235294, 5.88235294117647, 11.76470588235294, 17.647058823529413, 11.76470588235294, 5.88235294117647, 11.76470588235294, 11.76470588235294]
    
    return render_template('main/time.html', 
                           split_stations=split_stations, split_congestion=split_congestion,
                           split_minute=split_minute, percent_ls=percent_ls, lane=lane, station_ls=station_ls,
                           color_ls=color_ls)

WEB/templates/main.html
<!doctype html>

<html>
  <body>
  <p>main.html</p>

  <div>
    <br>
    <button type="button" onClick="location.href='time'"> 시간별 혼잡도 예상 </button>
  </div>

</html>

WEB/templates/main/time.html
<!doctype html>

<html>
<link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">
  <head>

  </head>
  <body style="background-color: #E7F2FE">
    <div class="box-sizing">

      <h1>쾌적한 길찾기</h1>
      
        <form action="{{ url_for('time.result') }}" method="POST">
          <div style="display: flex; align-items: center;">
            <input type="text" name="start_station" class="input-box start-station" placeholder="시작역" required>
            <span type="button" id="swap-button">
              <img src="../static/images/swap.png" alt="스왑 이미지" style="width: 50px; height: 50px;">
            </span>
            <input type="text" name="end_station" class="input-box end-station" placeholder="도착역" required>
          </div>

          <span class="time" id="selected-time"></span>

            <div class="timeset_option timeset_option_hour">
              <button class="timeset_btn_prev" onclick="changeHour(-1)"><span class="icon">이전</span></button>
              <div>
                <button class="timeset_btn_data" onclick="toggleHourLayer()">
                  <span class="btn_inner" id="hourValue">00시</span>
                </button>
                <!-- 시간 선택 리스트 -->
                <div class="layer_timeset hour" hidden="">
                  <div class="wrap_scroll">
                    <ul class="layer_timeset_list">
                      <!-- 시간 선택 버튼들은 이곳에 추가 -->
                      <li><button class="selected" onclick="setHour(0)">00</button></li>
                      <li><button onclick="setHour(1)">01</button></li>
                      <li><button onclick="setHour(2)">02</button></li>
                      <li><button onclick="setHour(3)">03</button></li>
                      <li><button onclick="setHour(4)">04</button></li>
                      <li><button onclick="setHour(5)">05</button></li>
                      <li><button onclick="setHour(6)">06</button></li>
                      <li><button onclick="setHour(7)">07</button></li>
                      <li><button onclick="setHour(8)">08</button></li>
                      <li><button onclick="setHour(9)">09</button></li>
                      <li><button onclick="setHour(10)">10</button></li>
                      <li><button onclick="setHour(11)">11</button></li>
                      <li><button onclick="setHour(12)">12</button></li>
                      <li><button onclick="setHour(13)">13</button></li>
                      <li><button onclick="setHour(14)">14</button></li>
                      <li><button onclick="setHour(15)">15</button></li>
                      <li><button onclick="setHour(16)">16</button></li>
                      <li><button onclick="setHour(17)">17</button></li>
                      <li><button onclick="setHour(18)">18</button></li>
                      <li><button onclick="setHour(19)">19</button></li>
                      <li><button onclick="setHour(20)">20</button></li>
                      <li><button onclick="setHour(21)">21</button></li>
                      <li><button onclick="setHour(22)">22</button></li>
                      <li><button onclick="setHour(23)">23</button></li>
                    </ul>
                  </div>
                </div>
              </div>
              <button class="timeset_btn_next" onclick="changeHour(1)"><span class="icon">다음</span></button>
            </div>
            
            <!-- 분 선택 버튼 -->
            <div class="timeset_option timeset_option_minute">
              <button class="timeset_btn_prev" onclick="changeMinute(-5)"><span class="icon">이전</span></button>
              <div>
                <button class="timeset_btn_data" onclick="toggleMinuteLayer()">
                  <span class="btn_inner" id="minuteValue">00분</span>
                </button>
                <!-- 분 선택 리스트 -->
                <div class="layer_timeset minute" hidden="">
                  <div class="wrap_scroll">
                    <ul class="layer_timeset_list">
                      <!-- 분 선택 버튼들은 이곳에 추가 -->
                      <li><button class="selected" onclick="setMinute(0)">00</button></li>
                      <li><button onclick="setMinute(5)">05</button></li>
                      <li><button onclick="setMinute(10)">10</button></li>
                      <li><button onclick="setMinute(15)">15</button></li>
                      <li><button onclick="setMinute(20)">20</button></li>
                      <li><button onclick="setMinute(25)">25</button></li>
                      <li><button onclick="setMinute(30)">30</button></li>
                      <li><button onclick="setMinute(35)">35</button></li>
                      <li><button onclick="setMinute(40)">40</button></li>
                      <li><button onclick="setMinute(45)">45</button></li>
                      <li><button onclick="setMinute(50)">50</button></li>
                      <li><button onclick="setMinute(55)">55</button></li>              
                      <!-- 나머지 분 버튼들도 추가 -->
                    </ul>
                  </div>
                </div>
              </div>
              <button class="timeset_btn_next" onclick="changeMinute(5)"><span class="icon">다음</span></button>
            </div>
            <button class="timeset_btn_now" onclick="showSelectedTime()"><span class="btn_inner">이시간출발</span></button>
            <button class="timeset_btn_now" onclick="setToCurrentTime()"><span class="btn_inner">지금 출발</span></button>
        </form>
      </div>
    

    <div class="box-sizing2">
      <div class='box-sizing3'>
        <h3>추천시간</h3>

        <div class='subway-box'>
          {% for percent in percent_ls %}
            {% set station = station_ls[loop.index0] %}
              <div class='congestion red' style='top: 0%; left: {{ percent }}%;'>
                <div class='center-white'>혼잡</div>
                <div class='station-name' style='top: 0%; left: {{ percent }}%;'>
                  <br><br>{{ station }}
                </div>
              </div>
          {% endfor %}
        </div>

        <br>
        <br>

        <h3>혼잡도</h3>
          <div class='congestion-red'>
            <div class='center-white2'>혼잡</div>
          </div>
          <div class='congestion-green'>
            <div class='center-black2'>여유</div>
          </div>
          <div class='congestion-blue'>
            <div class='center-black2'>보통</div>
          </div>
      </div>
    </div>


    <script>
      const horizontalPercentage = {{ horizontal_percentage }}; // horizontal_percentage 값이 이미 할당되어 있다고 가정합니다.
        const colorIndex = {{ color_index }}; // color_index 값이 이미 할당되어 있다고 가정합니다.

        const congestionRed = document.querySelector('.congestion');
        const subwayBoxWidth = document.querySelector('.subway-box').clientWidth;
        const congestionRedWidth = congestionRed.clientWidth;
        const maxLeft = subwayBoxWidth - congestionRedWidth;

        const calculateLeft = (percentage) => (percentage / 100) * maxLeft;
        const setLeftPosition = (percentage) => {
            const leftPosition = calculateLeft(percentage);
            congestionRed.style.left = `${leftPosition}px`;
        };

        setLeftPosition(horizontalPercentage);

        const colorClasses = ['blue', 'red', 'green'];
        const setColorClass = (index) => {
            congestionRed.classList.remove(...colorClasses);
            congestionRed.classList.add(colorClasses[index]);
        };

        setColorClass(colorIndex);

        const stationName = document.querySelector('.station-name');
        const subwayBox2Width = document.querySelector('.subway-box2').clientWidth;
        const stationNameRedWidth = congestionRed.clientWidth;
        const maxLeft = subwayBox2Width - stationNameRedWidth;

        const calculateLeft = (percentage) => (percentage / 100) * maxLeft;
                const setLeftPosition2 = (percentage) => {
                    const leftPosition = calculateLeft(percentage);
                    stationName.style.left = `${leftPosition}px`;
                };

        setLeftPosition2(horizontalPercentage);
    </script>

    <script src="../../static/js/time.js"></script>
    <script src="../../static/js/swap.js"></script>

    </body>

</html>